In [1]:
import os
os.chdir("D:/Flood_Project/Model_running/Trail Run -1/Input/Network/Reducing Capacity and Speed on link")

In [2]:
import geopandas as gpd
import pandas as pd
from shapely import wkt
import fiona
from fiona.crs import from_epsg

In [3]:
gdf = gpd.read_file('road.shp')

In [4]:
gdf

,ID,DIR,LENGTH,AB_LANES,BA_LANES,CENT_LANE,MODE_ID,NFC,NFC_FLAG,AREA_TYPE,...,AB_MDFB,AB_PMFB,AB_EVFB,AB_NTFB,BA_AMFB,BA_MDFB,BA_PMFB,BA_EVFB,BA_NTFB,geometry
0,5439,0,0.504171,1,1,0,2,4,None,5,...,36.520744,40.0,40.0,40.0,36.407935,37.297241,40.0,40.0,40.0,"LINESTRING (-83.89233 42.46190, -83.89132 42.4..."
1,7044,0,2.780595,1,1,0,2,5,None,5,...,29.999964,30.0,30.0,30.0,29.999997,29.999974,30.0,30.0,30.0,"LINESTRING (-83.88549 42.55560, -83.88962 42.5..."
2,7052,0,1.131603,1,1,0,2,5,None,5,...,29.980669,30.0,30.0,30.0,29.961160,29.989194,30.0,30.0,30.0,"LINESTRING (-83.89452 42.60478, -83.89436 42.6..."
3,7092,0,1.249086,1,1,0,2,3,None,5,...,42.778563,50.0,50.0,50.0,33.176405,42.156981,50.0,50.0,50.0,"LINESTRING (-83.89783 42.62257, -83.89557 42.6..."
4,7160,0,0.237102,2,2,1,2,3,None,4,...,39.916674,40.0,40.0,40.0,39.684849,39.643178,40.0,40.0,40.0,"LINESTRING (-83.88918 42.59226, -83.88501 42.5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35290,41308,1,0.279421,1,0,0,2,9,None,3,...,19.999904,20.0,20.0,20.0,NaN,NaN,NaN,NaN,NaN,"LINESTRING (-83.71840 42.29020, -83.71829 42.2..."
35291,41309,0,0.192161,1,1,0,2,9,None,3,...,12.762392,20.0,20.0,20.0,19.835742,16.875642,20.0,20.0,20.0,"LINESTRING (-83.71296 42.28753, -83.71295 42.2..."
35292,41310,-1,0.281037,0,1,0,2,9,None,3,...,NaN,NaN,NaN,NaN,20.000000,19.999988,20.0,20.0,20.0,"LINESTRING (-83.71845 42.29039, -83.71816 42.2..."
35293,41311,0,0.005314,1,1,0,2,9,None,3,...,12.762392,20.0,20.0,20.0,19.873008,17.892897,20.0,20.0,20.0,"LINESTRING (-83.71296 42.29031, -83.71296 42.2..."
35294,41312,0,0.291763,1,1,0,2,9,None,3,...,20.000000,20.0,20.0,20.0,19.998036,20.000000,20.0,20.0,20.0,"LINESTRING (-83.71296 42.29039, -83.71278 42.2..."

In [5]:
target_ids = [13470, 33109, 17300, 33534, 33486, 15052, 13031, 12673, 24069, 21815, 17301, 12672, 30709, 30984, 22833, 19199, 13851, 13673, 23519, 19420, 33108, 13703, 30978, 19436, 13061, 13355, 23256, 23868, 22831, 12534, 17221, 23863, 18309, 14124, 13806, 33096, 23182, 15716, 12803, 15072, 23277, 33375, 12698, 33519, 33236, 30460, 22460, 17317, 14479, 13280, 14030, 18531, 14132, 33161, 13973, 19192, 17213, 33103, 15423, 22885, 23522, 14146, 23861, 13205, 22810, 21631, 13899, 17296, 22947, 30739, 12149, 21370, 22870, 13699, 13790, 13667, 13793, 13365, 18198, 12881, 14011, 17320, 21632, 22889, 23429, 30719, 30731, 13359, 22404, 13709, 13934, 23873, 23437, 23086, 23087, 17161, 39946, 21626, 33665, 13194, 14167, 31004, 14413, 13911, 13457, 14453, 33856, 17337, 13190, 19456, 17305, 33526, 22567, 23430, 23177, 22941, 13648, 23465, 30728, 23106, 30730, 17330, 24233, 32993, 15352, 30710, 30996, 22744, 22806, 14064, 21483, 14128, 24386, 12695, 14409, 14319, 17913, 13199, 13265, 31996, 22742, 23470, 33208, 14001, 21486, 12150, 23142, 14417, 22302, 19441, 21868, 23174, 19446, 23326, 14113, 22741, 13375, 23869, 22922, 12010, 39963, 30999, 24227, 22953, 13727, 30514, 21089, 39960, 17800, 19421, 24299, 22635, 13862, 23243, 22405, 30443, 33509, 30986, 18348, 22086, 23597, 17218, 39955, 21542, 17318, 23867, 11994, 13840, 13206, 30504, 22585, 13932, 33528, 13258, 18527, 33459, 12702, 22883, 24273, 33368, 13054, 13992, 22948, 13029, 33857, 22593, 22951, 22618, 13841, 18521, 21752, 14116, 13801, 15231, 13838, 22526, 13975, 22451, 14290, 30985, 14191, 22193, 14277, 13999, 18023, 14467, 30976, 14164, 23223, 17313, 17223, 17306, 24399, 14272, 23517, 22407, 23821, 12699, 13662, 30296, 22527, 21482, 23870, 14326, 14179, 22809, 13688, 17155, 22672, 17923, 13360, 33453, 22591, 30979, 21872, 30994, 33538, 30720, 23866, 23590, 30305, 33237, 22811, 14440, 24292, 14223, 23601, 22528, 14379, 22887, 14079, 14080, 30298, 14317, 15451, 30989, 33501, 15031, 23823, 23432, 18308, 14415, 15053, 18523, 13033, 24135, 31003, 22578, 13850, 19418, 13773, 22731, 30506, 14336, 33523, 33367, 22462, 19207, 13735, 30725, 33385, 23665, 30746, 33912, 30718, 14083, 22671, 40678, 33373, 17326, 30726, 13736, 23090, 33167, 22586, 33158, 22674, 33116, 13664, 12877, 17160, 13707, 17803, 23600, 33093, 13256, 33157, 17338, 23864, 30712, 13849, 22529, 30714, 33105, 22596, 30758, 23662, 13676, 13823, 14119, 33475, 17159, 24239, 23101, 30595, 12152, 13659, 12521, 33102, 13663, 14411, 13978, 23260, 14232, 14300, 33662, 39956, 19443, 17327, 14185, 21753, 24213, 33516, 14135, 22195, 39958, 17163, 30992, 39950, 13274, 14104, 24132, 17156, 12676, 13749, 22829, 23822, 12690, 23598, 13733, 19423, 18590, 14067, 30715, 22830, 23278, 14250, 13257, 33520, 14003, 33377, 17312, 14401, 17165, 12523, 17322, 33515, 33110, 13674, 13852, 13718, 33518, 22650, 14230, 24269, 22406, 33154, 22886, 17329, 33306, 33908, 19440, 24414, 15442, 13058, 33090, 23641, 14421, 17328, 13944, 17324, 30455, 19438, 19271, 12790, 30717, 12995, 33911, 21588, 30993, 33517, 23485, 12174, 17168, 23872, 18120, 13955, 33504, 31000, 33117, 13936, 30732, 23319, 13900, 39957, 18525, 33508, 30505, 12003, 17222, 23514, 17169, 19428, 17922, 23820, 23865, 30511, 13760, 30508, 17335, 12617, 13993, 13890, 30509, 17323, 39965, 22856, 14340, 21067, 17798, 22229, 13905, 14388, 22589, 22769, 33386, 15067, 33420, 33130, 33531, 14014, 30297, 33500, 14449, 33155, 22402, 17955, 13856, 17321, 24187, 22532, 22787, 13805, 23093, 14093, 13956, 30727, 21377, 33098, 12875, 18352, 17758, 13969, 23167, 13193, 22639, 12885, 21946,
             13200, 13797, 14099, 22834, 30975, 19419, 19444, 12154, 14456, 33160, 22815, 33234, 23176, 12871, 17212, 30998, 31010, 22453, 12529, 33374, 39951, 22739, 33540, 18371, 14321, 12966, 23473, 14173, 23602, 23583, 17336, 24333, 24408, 33162, 14241, 33209, 33825, 22795, 22400, 30729, 12787, 15054, 22949, 13362, 33831, 30769, 17315, 14383, 30743, 14448, 33521, 13895, 12009, 14451, 23467, 22940, 17298, 13032, 18205, 30380, 33492, 22746, 14091, 22196, 19445, 17325, 13951, 13690, 12070, 22408, 14332, 14359, 30991, 15758, 13927, 13071, 13767, 23599, 33669, 17157, 22771, 23220, 13940, 22081, 30733, 22577, 22828, 13772, 13807, 17170, 23653, 33506, 22458, 23502, 30977, 18189, 30526, 24426, 17340, 23427, 33106, 33371, 14029, 30724, 30988, 17314, 13781, 30987, 33510, 19442, 14358, 24517, 30721, 14136, 23023, 13353, 23570, 13902, 13883, 14165, 14444, 14458, 14236, 33474, 21591, 30741, 33156, 12060, 13030, 22588, 13654, 22882, 33502, 33513, 23332, 12797, 19439, 14125, 22401, 14352, 33458, 23444, 13742, 33233, 12068, 24361, 33111, 18094, 23021, 13909, 12957, 23431, 17297, 34123, 13943, 33910, 33378, 22770, 23434, 22772, 18296, 22827, 13660, 13695, 33384, 30299, 23466, 13270, 30295, 33666, 30722, 24237, 22085, 33511, 33503, 12971, 33487, 39954, 23231, 18343, 23824, 14171, 30980, 30997, 22454, 22807, 23472, 33362, 13278, 12536, 17294, 30510, 17162, 18604, 23596, 23255, 13863, 24117, 30745, 17333, 22749, 23178, 17308, 23001, 22030, 12615, 31700, 33118, 13804, 14408, 23026, 23084, 19435, 23085, 39959, 23259, 17332, 23179, 14015, 13694, 13792, 13768, 23327, 30507, 14384, 11993, 23654, 33527, 13897, 19201, 33101, 14478, 13926, 24238, 23244, 13946, 22997, 13665, 22463, 23407, 30301, 22679, 13708, 13744, 40680, 13976, 12879, 18311, 31002, 22190, 18314, 22808, 13741, 14226, 24240, 18265, 23474, 22194, 23018, 17310, 24226, 33498, 24234, 14145, 14032, 21277, 23516, 23518, 30981, 23584, 33457, 13865, 14089, 18199, 17158, 19125, 33668, 21951, 23670, 24118, 22403, 13941, 13745, 22525, 13198, 23871, 13877, 13885, 14074, 23512, 33505, 30723, 18397, 13774, 21487, 13866, 22884, 15073, 30734, 13196, 13711, 23825, 13918, 13824, 14346, 22670, 22832, 14246, 17171, 14330, 22812, 17303, 22192, 22740, 13855, 13871, 23328, 19422, 24397, 33123, 23663, 13652, 23175, 13921, 39961, 33104, 33383, 17166, 30512, 17316, 22455, 33231, 25535, 23275, 22511, 23330, 30742, 21755, 13765, 21376, 18108, 22926, 22191, 14414, 13952, 13653, 13901, 30501, 33529, 23088, 33664, 33535, 33830, 13782, 19454, 17164, 22587, 14347, 33100, 19200, 14183, 13848, 13939, 33667, 13964, 12674, 33663, 23232, 14061, 24230, 13881, 17763, 12874, 12692, 12675, 13063, 18532, 18119, 22456, 13681, 12057, 19437, 13276, 22804, 33091, 30594, 33473, 17331, 17961, 13730, 33536, 22590, 14021, 33380, 13277, 18118, 13683, 23667, 39966, 30995, 22676, 23072, 23274, 23234, 30735, 22303, 23160, 13737, 13752, 22584, 30711, 17304, 15049, 15058, 14213, 23515, 18529, 14470, 22651, 23180, 19455, 13743, 19453, 12888, 17167, 33094, 13880, 23335, 14046, 30300, 33909, 21754, 33476, 30713, 22594, 23258, 13748, 14187, 22822, 30262, 14462, 40676, 13889, 17309, 31001, 14097, 13935, 23320, 17311, 15065, 33530, 13796, 30513, 33107, 23325, 33099, 33097, 13706, 33514, 14180, 30990, 17334, 13922, 23236, 18181, 33095, 33507, 13052, 13371, 33539, 17295, 33159, 13756, 30716, 30744, 33533, 23019, 24363, 17319, 13339, 13729, 22592, 13657]

In [6]:
# Reduce only for rows where the 'ID' is in target_ids
columns_to_reduce = [
    'AB_FFS', 'BA_FFS', 'AB_DYCAP', 'BA_DYCAP', 'AB_AMCAP', 'BA_AMCAP', 
    'AB_MDCAP', 'BA_MDCAP', 'AB_PMCAP', 'BA_PMCAP', 'AB_EVCAP', 'BA_EVCAP', 
    'AB_NTCAP', 'BA_NTCAP'
]

# Apply the 20% reduction only to rows with IDs in target_ids
gdf.loc[gdf['ID'].isin(target_ids), columns_to_reduce] *= 0.8

In [8]:
# Display the row with ID = 13200 in the GeoDataFrame (gdf)
row_with_id_13200 = gdf[gdf['ID'] == 13200]
row_with_id_13200['AB_DYCAP']

22106    12000.0
Name: AB_DYCAP, dtype: float64

In [9]:
gdf.to_file('road_update_grant_area.shp')